// Copies the assets shared with the Next.js web app into mobile/ so the
// two frontends stay in lockstep (spec §4.4). Flutter can't reliably reach
// assets outside its project root, so we vendor a checked copy instead of
// symlinking.
//
//   dart run tool/sync_shared_assets.dart          # copy
//   dart run tool/sync_shared_assets.dart --check   # CI: fail if stale
//
// Sources (all relative to the repo root, mobile/..):
//   app/locales/{en,es,definitions-en,definitions-es}.json
//   app/_fonts/*.ttf
//   public/win.mp3
//   app/lib/epoch.ts            -> lib/src/epoch.dart  (generated const)
//   app/lib/api/v1-schema.json
//   app/lib/mobile-parity.fixture.json -> test/fixtures/parity.json

import 'dart:convert';
import 'dart:io';

final repoRoot = Directory.current.path.endsWith('/mobile')
    ? Directory(Directory.current.parent.path)
    : Directory.current;

String _root(String p) => '${repoRoot.path}/$p';
String _mobile(String p) => '${repoRoot.path}/mobile/$p';

/// (sourceBytes, destPath) pairs. Source is computed eagerly so --check and
/// the real copy share exactly one definition of "what should be there".
class _Target {
  _Target(this.dest, this.bytes, this.from);
  final String dest;
  final List<int> bytes;
  final String from;
}

List<_Target> _plan() {
  final targets = <_Target>[];

  void copy(String from, String to) {
    final src = File(_root(from));
    if (!src.existsSync()) {
      stderr.writeln('missing source: $from');
      exit(2);
    }
    targets.add(_Target(_mobile(to), src.readAsBytesSync(), from));
  }

  for (final name in ['en', 'es', 'definitions-en', 'definitions-es']) {
    copy('app/locales/$name.json', 'assets/locales/$name.json');
  }
  for (final f in Directory(_root('app/_fonts')).listSync().whereType<File>()) {
    if (f.path.endsWith('.ttf')) {
      copy('app/_fonts/${f.uri.pathSegments.last}',
          'assets/fonts/${f.uri.pathSegments.last}');
    }
  }
  copy('public/win.mp3', 'assets/audio/win.mp3');
  copy('app/lib/api/v1-schema.json', 'assets/shared/v1-schema.json');
  copy('app/lib/mobile-parity.fixture.json', 'test/fixtures/parity.json');

  // EPOCH: parse the single string literal out of the TS module and emit a
  // Dart const so the ports and parity tests share one source of truth.
  final epochTs = File(_root('app/lib/epoch.ts')).readAsStringSync();
  final m = RegExp('EPOCH\\s*=\\s*"([0-9]{4}-[0-9]{2}-[0-9]{2})"').firstMatch(epochTs);
  if (m == null) {
    stderr.writeln('could not parse EPOCH from app/lib/epoch.ts');
    exit(2);
  }
  final epochDart = '// GENERATED by tool/sync_shared_assets.dart from '
      'app/lib/epoch.ts. Do not edit.\n'
      "const String kEpoch = '${m.group(1)}';\n";
  targets.add(_Target(_mobile('lib/src/epoch.dart'), utf8.encode(epochDart), 'app/lib/epoch.ts'));

  return targets;
}

bool _sameBytes(List<int> a, List<int> b) {
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}

void main(List<String> args) {
  final check = args.contains('--check');
  final targets = _plan();
  final stale = <String>[];

  for (final t in targets) {
    final dest = File(t.dest);
    final current = dest.existsSync() ? dest.readAsBytesSync() : null;
    final ok = current != null && _sameBytes(current, t.bytes);
    if (ok) continue;
    if (check) {
      stale.add('${t.dest.replaceFirst('${repoRoot.path}/', '')}  (from ${t.from})');
      continue;
    }
    dest.parent.createSync(recursive: true);
    dest.writeAsBytesSync(t.bytes);
    stdout.writeln('wrote ${t.dest.replaceFirst('${repoRoot.path}/', '')}');
  }

  if (check && stale.isNotEmpty) {
    stderr.writeln('shared assets are stale — run:\n'
        '  dart run tool/sync_shared_assets.dart\n');
    for (final s in stale) {
      stderr.writeln('  $s');
    }
    exit(1);
  }
  if (check) stdout.writeln('shared assets up to date (${targets.length} files)');
}
